import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css'
import styles from '../styles/Home.module.css'
import { useStoryblokState, getStoryblokApi, StoryblokComponent } from '@storyblok/react'

export default function Page({ story }: any) {
  story = useStoryblokState(story)

  return (
    <div className={styles.container}>
      <Head>
        <title>{story ? story.name : 'My Site'}</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>{story ? story.name : 'My Site'}</h1>
      </header>

      <main className={styles.main}>
        <StoryblokComponent blok={story.content} />
      </main>
    </div>
  )
}

export async function getStaticProps({ params }: any) {
  const slug = params.slug ? params.slug.join('/') : 'home'

  const sbParams = {
    version: 'draft', // or 'published'
  }

  const storyblokApi = getStoryblokApi()
  const { data } = await storyblokApi.get(`cdn/stories/${slug}`, sbParams)

  return {
    props: {
      story: data ? data.story : false,
      key: data ? data.story.id : false,
    },
    revalidate: 3600,
  }
}

export async function getStaticPaths() {
  const storyblokApi = getStoryblokApi()
  const { data } = await storyblokApi.get('cdn/links/')
  const paths: any = []

  Object.keys(data.links).forEach((linkKey) => {
    if (data.links[linkKey].is_folder || data.links[linkKey].slug === 'home') {
      return
    }

    const slug = data.links[linkKey].slug
    const splittedSlug = slug.split('/')
    paths.push({ params: { slug: splittedSlug } })
  })

  return {
    paths: paths,
    fallback: false,
  }
}

// export default function Home({ story: initialStory }: any) {
//   const story: any = useStoryblokState(initialStory)

//   if (!story.content) {
//     return <div>Loading...</div>
//   }

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <header>
//         <h1>{story ? story.name : 'My Site'}</h1>
//       </header>

//       <Navbar bg="light" expand="lg">
//         <Container>
//           <Navbar.Brand href="#home">React-Bootstrap</Navbar.Brand>
//           <Navbar.Toggle aria-controls="basic-navbar-nav" />
//           <Navbar.Collapse id="basic-navbar-nav">
//             <Nav className="me-auto">
//               <Nav.Link href="#home">Home</Nav.Link>
//               <Nav.Link href="#link">Link</Nav.Link>
//             </Nav>
//           </Navbar.Collapse>
//         </Container>
//       </Navbar>

//       <main className={styles.main}>
//         <h1 className={styles.title}>{story ? story.name : 'My Site'}</h1>
//         <ul className={styles.navbar}>
//           <li>
//             <Link href="/ssg">
//               <a>ssg page</a>
//             </Link>
//           </li>
//           <li>
//             <Link href="/ssr">
//               <a>ssr page</a>
//             </Link>
//           </li>
//           <li>
//             <Link href="/csr-swr">
//               <a>csr page</a>
//             </Link>
//           </li>
//         </ul>
//         <StoryblokComponent blok={story.content} />
//       </main>
//     </div>
//   )
// }

// export async function getStaticProps() {
//   // the slug of the story
//   const slug = 'home'

//   const params = {
//     version: 'draft', // or 'published'
//   }

//   const storyblokApi = getStoryblokApi()
//   const { data } = await storyblokApi.get(`cdn/stories/${slug}`, params)

//   return {
//     props: {
//       story: data ? data.story : false,
//       key: data ? data.story.id : false,
//     },
//   }
// }
