import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import fetcher from '../functions/fetcher'

function CsrSWR() {
  const { data, error } = useSWR('missions', fetcher)

  if (error) return <div>Error... failed to load</div>
  if (!data) return <div>Loading...</div>

  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Client side rendering page SWR hook</h1>
        <h2>Missions</h2>
        <>
          {data.map((mission: any) => {
            return (
              <div key={mission.id}>
                <h2>{mission.mission_name}</h2>
                <div className={styles.dflexcol}>
                  <span>{mission.description}</span>
                </div>
              </div>
            )
          })}
        </>
      </main>
    </div>
  )
}

export default CsrSWR
