import { useState, useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

function Csr() {
  const [isLoading, setIsLoading] = useState(true)
  const [spaceData, setSpaceData] = useState(null)

  useEffect(() => {
    async function fetchSpaceData() {
      const response = await fetch('https://api.spacexdata.com/v3/missions')
      const data = await response.json()
      setSpaceData(data)
      setIsLoading(false)
    }
    fetchSpaceData()
  }, [])

  if(isLoading) {
    return <h2>Loading ...</h2>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Client side rendering page</h1>
        <h2>Missions</h2>
        <>
            {
              spaceData.map(mission => {
                return (
                  <div key={mission.id}>
                    <h2>
                      {mission.mission_name}
                    </h2>
                    <div className={styles.dflexcol}>
                      <span>{mission.description}</span>
                    </div>
                  </div>
                )
              })
            }
          </>
      </main>
    </div>
  )
}


export default Csr
