import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useStoryblokState, getStoryblokApi, StoryblokComponent } from '@storyblok/react'

export default function Home({ story: initialStory }: any) {
  const story = useStoryblokState(initialStory)

  console.log(story)

  if (!story.content) {
    return <div>Loading...</div>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>{story ? story.name : 'My Site'}</h1>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>Homepage</h1>
        <ul className={styles.navbar}>
          <li>
            <Link href="/ssg">
              <a>ssg page</a>
            </Link>
          </li>
          <li>
            <Link href="/ssr">
              <a>ssr page</a>
            </Link>
          </li>
          <li>
            <Link href="/csr-swr">
              <a>csr page</a>
            </Link>
          </li>
        </ul>
      </main>

      <StoryblokComponent blok={story.content} />
    </div>
  )
}

export async function getStaticProps() {
  // the slug of the story
  let slug = 'home'

  let params = {
    version: 'draft', // or 'published'
  }

  const storyblokApi = getStoryblokApi()
  let { data } = await storyblokApi.get(`cdn/stories/${slug}`, params)

  return {
    props: {
      story: data ? data.story : false,
      key: data ? data.story.id : false,
    },
  }
}
