import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Homepage</h1>
        <ul className={styles.navbar}>
          <li>
            <Link href="/ssg">
              <a>ssg page</a>
            </Link>
          </li>
          <li>
            <Link href="/ssr">
              <a>ssr page</a>
            </Link>
          </li>
          <li>
            <Link href="/csr-swr">
              <a>csr page</a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  )
}

export default Home
